from typing import Any

SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "name": "Reddit operator discussions",
        "slug": "reddit-operators",
        "description": "Operator complaints, workarounds, and recurring workflow discussions.",
        "source_type": "community",
        "adapter_key": "reddit_apify",
        "actor_env": "APIFY_REDDIT_ACTOR_ID",
        "reliability_weight": 0.62,
        "collector_config": {"document_type": "reddit_post", "queries": []},
    },
    {
        "name": "Industry news",
        "slug": "industry-news",
        "description": "News and trade-publication changes feeding the Foresight Radar.",
        "source_type": "news",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.58,
        "collector_config": {"mode": "rss", "document_type": "news_article", "startUrls": []},
    },
    {
        "name": "Regulatory notices",
        "slug": "regulatory-notices",
        "description": "Government and regulator notices that create mandatory workflows.",
        "source_type": "regulation",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.95,
        "collector_config": {"mode": "rss", "document_type": "regulatory_notice", "startUrls": []},
    },
    {
        "name": "Product changelogs",
        "slug": "product-changelogs",
        "description": "Platform, API, pricing, and product capability changes.",
        "source_type": "changelog",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.82,
        "collector_config": {"mode": "pages", "document_type": "changelog_entry", "startUrls": []},
    },
    {
        "name": "Job postings",
        "slug": "job-postings",
        "description": "Recurring human duties, tools, salaries, and hiring volume.",
        "source_type": "jobs",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.88,
        "collector_config": {"mode": "pages", "document_type": "job_posting", "startUrls": []},
    },
    {
        "name": "Software reviews",
        "slug": "software-reviews",
        "description": "Verified complaints and missing capabilities in incumbent products.",
        "source_type": "reviews",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.8,
        "collector_config": {"mode": "pages", "document_type": "software_review", "startUrls": []},
    },
    {
        "name": "Niche forums",
        "slug": "niche-forums",
        "description": "Industry-specific operator conversations and shadow workflows.",
        "source_type": "community",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.66,
        "collector_config": {"mode": "pages", "document_type": "forum_post", "startUrls": []},
    },
    {
        "name": "Agency and service pages",
        "slug": "agency-services",
        "description": "Recurring services and retainers that indicate existing spend.",
        "source_type": "services",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.78,
        "collector_config": {"mode": "pages", "document_type": "service_page", "startUrls": []},
    },
    {
        "name": "Template marketplaces",
        "slug": "template-marketplaces",
        "description": "Paid spreadsheets, trackers, checklists, and workflow templates.",
        "source_type": "templates",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.72,
        "collector_config": {"mode": "pages", "document_type": "template_listing", "startUrls": []},
    },
    {
        "name": "Competitor websites",
        "slug": "competitor-websites",
        "description": "Positioning, pricing, features, integrations, and market changes.",
        "source_type": "competitor",
        "adapter_key": "generic_apify",
        "actor_env": "APIFY_WEB_COLLECTOR_ACTOR_ID",
        "reliability_weight": 0.7,
        "collector_config": {"mode": "pages", "document_type": "competitor_page", "startUrls": []},
    },
]
